project:
  type: website

website:
  title: "Chad You"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Consulting"
        href: https://calendly.com/chadyou
  site-url: https://www.chadyou.com
  margin-header: subscribe.html
        
  page-footer: 
    background: light
    left: © Chad You. All rights reserved.
    right: This website is built with [Quarto](https://quarto.org)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
